### ISSUE TITLE
log an object/array

### ISSUE THREAD

**Issue by hayden-t** [frankforte/quantumphp#1]
i tried logging an object, and it just says, [object] what good is this. i need to be able to just log an array or object and the browse its structure like the good old days, if this just does text then why bether with it and not just use console.log() ....

**Comment by frankforte** [comment]
Thanks for reporting this!  I am pretty sure I had this working, but it's
possible I missed something.

Can you please send an example (PHP code) that results in just having
[object] appear in the browser console?

I'll try to apply a fix asap once I see what's wrong.


Frank

On Dec 6, 2017 9:48 PM, "hayden-t" <notifications@github.com> wrote:

i tried logging an object, and it just says, [object] what good is this. i
need to be able to just log an array or object and the browse its structure
like the good old days, if this just does text then why bether with it and
not just use console.log() ....

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/frankforte/quantumphp/issues/1>, or mute the thread

**Comment by hayden-t** [comment]
do you mean a hosted php file ?

**Comment by frankforte** [comment]
Yes, I am curious how the object is structured, and how you are sending the object.  For example:

```php
<?php

class Foo{
     public $bar = "hello";
     public $baz = ["items","in","array"];
}
$object = new Foo();

QuantumPHP::add($object);
QuantumPHP::send();

?>
```

If you can show me an example, I might be able to help.

**Comment by hayden-t** [comment]
it works after all, you didnt really say that when toe use ::add or ::log , add work but log doesnt

**Comment by frankforte** [comment]
Great. I added a note to the README so others are aware. Hopefully in a future release I can get objects to work with all logging methods.
